---
server_name: wardensmp
server_timezone: Europe/Moscow

minecraft_stack_root: /srv/wardensmp

domains:
  root: wardensmp.lolma.us
  minecraft: wardensmp.lolma.us
  website: wardensmp.lolma.us
  map: map.wardensmp.lolma.us
  admin: admin.wardensmp.lolma.us

allowed_tcp_ports:
  - 22
  - 80
  - 443
  - 25565
